import { createAsyncThunk } from "@reduxjs/toolkit";
import { ViewPopularSongsUseCase } from "./view-popular-Songs.usecase";

//This thunk is generated by generate-thunks.ts , please do not modify it manually
export const ViewPopularSongsThunk = createAsyncThunk(
  "view-popular-Songs/ViewPopularSongs",
  async (arg: { input: { maxNumber: number } }, { rejectWithValue }) => {
    try {
      const usecase = container.get(ViewPopularSongsUseCase);
      return await usecase.execute(arg.input);
    } catch (err) {
      return rejectWithValue(err);
    }
  },
);
